### ISSUE TITLE
Encrypting the file(s)

### ISSUE THREAD

**Issue by lasertunguus** [marinan87/smartsafe#1]
-     needs to be symmetric (key used for decryption)
-     best algo seems to be AES-256-CTR
-     maybe batch encryption (i.e using the same key for multiple files) option

**Acceptance criteria**:
- The used key should be saved to be used later in the process
- The file is encrypted and the same key can be used to decrypt the file

**Comment by lasertunguus** [comment]
- needs to be symmetric
- best algo seems to be AES-256-CTR
- maybe batch encryption (i.e using the same key for multiple files) option

**Comment by peeterkk** [comment]
> maybe batch encryption (i.e using the same key for multiple files) option

Not a good idea, unless the user specifically want this.

**Comment by lasertunguus** [comment]
@peeterkk This would be necessary since creating good keys (= having more entropy) needs time and if the user is set out to encrypt tens/hundreds/thousands files then just the process of gathering entropy would take too long.

**Comment by jakulikov** [comment]
lockbox already implemented this in client/src/utils/cryptoUtils::encrypt
Added password requirement for file enryption
