### ISSUE TITLE
Pushing notification about incoming file

### ISSUE THREAD

**Issue by marinan87** [marinan87/smartsafe#19]
As a Smartsafe user, I want to be notified when another user shares some of his/her files with me.

**Acceptance criteria**:
- A batch job (part of REST service) that checks periodically the table with pending links is implemented.
- Notifications about pending links are sent via WebSocket to all connected users.
- Corresponding records are deleted from table.
- Code is covered by unit and service tests.
- A manual integration test is performed.

_Additional information_:
This story is closely related to #10 (Evaluate usage of Spring WebSocket support for pushing notifications about new files) and might become obsolete in the light of new information obtained during working on #10.

**Comment by marinan87** [comment]
Postponed, because equivalent functionality might be implemented in the future solely on the client side.

**Comment by peeterkk** [comment]
This was replaced with https://github.com/marinan87/smartsafe/issues/79
