### ISSUE TITLE
Create basic project structure for REST service

### ISSUE THREAD

**Issue by marinan87** [marinan87/smartsafe#2]
As a Smartsafe developer, I want to have a basic project structure for RESTful service in place in order to start working on technical architecture tickets and implement new functionality.

**Acceptance criteria**:
- Initial hierarchy of project modules (directories, Maven modules, pom.xml files, etc.) is committed to repository.
- Basic Spring dependencies (sufficient to start a Spring Boot application) are configured.
- A small REST test application is prepared and committed.
- The instructions for setting up a local development environment (RESTful service part) are published to project Wiki on a 'Getting started' page. 
- Other team members are able to checkout the code, start the server locally and get JSON response from one URL.

**Comment by marinan87** [comment]
Done. Reviewer is welcome to try to set up local environment according to the instructions [here](https://github.com/marinan87/smartsafe/wiki/Getting-started#server-rest).

**Comment by lasertunguus** [comment]
`21:56:50.425 [main] INFO  com.smartsafe.Application - Started Application in 8.505 seconds (JVM running for 9.398)`
Verified.
