### ISSUE TITLE
Decrypting the file(s)

### ISSUE THREAD

**Issue by lasertunguus** [marinan87/smartsafe#20]
Using the saved symmetric keys - either in the locally saved keyring or in the blockchain - to decrypt the file with method specified in #1.

**Comment by lasertunguus** [comment]
- Decrypted file should be saved to location specified by user

**Comment by peeterkk** [comment]
#25 might replace this

**Comment by jakulikov** [comment]
As decided, this won't be replaced with #25 , because implementation of broadcast key for every receiver doesn't seem to be possible. At least, with our resources.
lockbox already implemented this in client/src/utils/cryptoUtils::decrypt
