### ISSUE TITLE
Hash for encrypted file

### ISSUE THREAD

**Issue by lasertunguus** [marinan87/smartsafe#21]
Calculate SHA-256 hash from outputted file from #1. This info (other info) will be published in the blockchain.
Does not need to be encrypted.

**Acceptance criteria**:
- Output of is a stringified version of 32-bytes (=256 bits), e.g 8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92

**Comment by jakulikov** [comment]
Can be implemented using node.js **crypto** library **Hash** class
Example from nodejs.org
`const crypto = require('crypto');
const hash = crypto.createHash('sha256');

hash.update('some data to hash');
console.log(hash.digest('hex'));
  // Prints:
  //   6a2da20943931e9834fc12cfe5bb47bbd9ae43489a30726962b576f4e3993e50`
