### ISSUE TITLE
File metadata retrieval from blockchain

### ISSUE THREAD

**Issue by lasertunguus** [marinan87/smartsafe#23]
Since #22 needs (at least) the hash of the file, the correct block->transaction/SC needs to be located in the blockchain.
The simple method would look through all transactions and check if their metadata in data field matches the hash calculated in #21.
Or the complex method would be using smart contracts in a clever way (possibly functionality for future versions).

**Acceptance criteria**:
- It's possible to retrieve metadata for a smartsafe file

**Comment by peeterkk** [comment]
[#26,#59] Fix #26 and #59
https://github.com/marinan87/smartsafe/commit/6f5ef222ec6bed5f04451f0dbbb477540b7865e2
