### ISSUE TITLE
File metadata creation

### ISSUE THREAD

**Issue by lasertunguus** [marinan87/smartsafe#24]
As by an example found in Metadisk's whitepaper, create the JSON-like metadata.
If the receiver downloads the link he should be able to retrieve the file and verify it by using the hash from the metadata.

Fields that need to be encrypted:
- download link
- symmetric key (if file is encrypted) 

**Acceptance criteria**:
- Contains timestamp, the link to the file, the hash from #21, file size
- If the file is encrypted (on by default) then the used symmetric key is appended
- Unit tested

**Comment by peeterkk** [comment]
@lasertunguus and @jakulikov -- timestamp?
