### ISSUE TITLE
Create the broadcast key from the public keys of the addressees and the file owner

### ISSUE THREAD

**Issue by peeterkk** [marinan87/smartsafe#25]
**Acceptance criteria:**
- You can use the Ethereum public keys of the users to generate a broadcast key

**Comment by peeterkk** [comment]
If we store the broadcast key on the chain, then we achieve independence from the DB. The problem with it is that you have to create a new transaction to give more/less people permissions -- however, do you think the user is going to feel the need to impulsively grant and revoke rights for files they want to be secure and private?.

In this case, the user only needs to share their ETH public key -- with which, the addressee will find the entry on the chain. If the DB goes down, the user can read the public key using the app -- to access ETH chain -- and send it to the addressee via email.

**Comment by jakulikov** [comment]
Ethereum public keys aren't supposed to be used outside ethereum.
Moreover, I didn't find the way to implement broadcast key, so another encryption technique will be used.
