### ISSUE TITLE
Store meta-data on the chain

### ISSUE THREAD

**Issue by peeterkk** [marinan87/smartsafe#26]
Everything is added into the blockchain via transaction creation for which Web3.js is used
Encryption is done using the private and public keys that are generated for each users by our app (not the ones created on the blockchain).

**Acceptance criteria:**
- The encrypted timestamp
- The encrypted file hash
- The encrypted link to Dropbox
- The broadcast key (iteration3)

**Comment by lasertunguus** [comment]
@peeterkk, @jakulikov please elaborate on the broadcast key

**Comment by lasertunguus** [comment]
Use output from #24
