### ISSUE TITLE
Encrypting the symmetric key with the Public Key of the receiver

### ISSUE THREAD

**Issue by lasertunguus** [marinan87/smartsafe#33]
The symmetric key published to blockchain needs to be encrypted for additional security.
The access to this key should only be restricted to the sending and receiving parties.
Similarities to PGP.

**Acceptance criteria:**
- The key generated for #1 is encrypted with the receiver's public key
- Unit test with asymmetric key pair

**Comment by jakulikov** [comment]
The password used for symmetric key generation is encrypted, but not saved to database yet, thus hardcoded password is used by now. [commit](https://github.com/marinan87/smartsafe/commit/6968e342e59f8381f99efa407da5aeeba10d9b72)
