### ISSUE TITLE
Uploading of (encrypted) file to Dropbox

### ISSUE THREAD

**Issue by lasertunguus** [marinan87/smartsafe#34]
Use the Dropbox API to upload the file from #1 to the cloud under the user's account. Progress should be displayed.
This could be done by putting the file to Dropbox folder. This would remove the duplicate work that DB would do for downloading the same file.
The API should be polled for status.
An (encrypted) file should be uploaded to the user's Dropbox account. The user should be shown progress of this process and preferably notified when it finishes.
**Acceptance criteria**:
- DB API reports the file being uploaded
- Integration test for uploading and downloading the same file and checking it's integrity

**Comment by jakulikov** [comment]
Encrypted file uploading is implemented: [commit](https://github.com/marinan87/smartsafe/commit/d9e1e0594a966f6b4258b82079bd526c078340e7)
