### ISSUE TITLE
View for uploading file(s)

### ISSUE THREAD

**Issue by LiisiMotsharg** [marinan87/smartsafe#36]
**Aceptance criteria**
- User should be able to choose file they with to upload from their local drive
- User can choose if they want to encrypt file(s) and which ones
- The list is updated if user adds/removes a file
- There is a button to start uploading files
- There is/are button(s) to cancel uploading
- Upload progress is displayed to the user (show progressbar, percentage or both)
- User is notified if all current uploads are complete

**Comment by peeterkk** [comment]
@LiisiMotsharg  remember, encryption was supposed to be an option

**Comment by LiisiMotsharg** [comment]
Done with some exceptions: 
* Upload progress is displayed to the user (show progressbar, percentage or both) - currently progress is not shown to user due to technical difficulties in getting progress information, see task #38 
* User is notified if all current uploads are complete - Not done yet, see task #75
