### ISSUE TITLE
Showing upload progress to user

### ISSUE THREAD

**Issue by LiisiMotsharg** [marinan87/smartsafe#38]
**Acceptance criteria**
- Upload progress is displayed to the user (show progressbar, percentage or both)
- User is notified if all current uploads are complete

**Comment by lasertunguus** [comment]
Is related to #34.

**Comment by peeterkk** [comment]
Merged with #36

**Comment by LiisiMotsharg** [comment]
Reopened because implementation is difficult enough to warrant separate task.

**Comment by LiisiMotsharg** [comment]
User is notified (by showing a green checkmark and appropriate status message) when file is uploaded. Won't do showing upload progress, since it would require getting realtime info about upload progress from Dropbox API upload method, which is not supported right now.
