### ISSUE TITLE
Publish file metadata to blockchain

### ISSUE THREAD

**Issue by lasertunguus** [marinan87/smartsafe#39]
Output from #24 should be saved either as in a new transaction data field or as a smart contract (this is a open path; 1st option seems to be easier to implement, but with limited functionality).
The transaction/smart contract should somehow indicate the recipient (transaction to certain address that belongs to user).

**Acceptance criteria**:
_Needs more investigation_

**Comment by lasertunguus** [comment]
Duplicate

**Comment by peeterkk** [comment]
@lasertunguus What's the duplicate?
