### ISSUE TITLE
Displaying a list of files the user has in app folder on Dropbox

### ISSUE THREAD

**Issue by LiisiMotsharg** [marinan87/smartsafe#42]
**Acceptance criteria**
- User is shown a list of all the files he has in his Dropbox folder
- Each file has number, which shows how many people this file is shared with
- Each file has at least name, location, time and date of creation
- Clicking on a file opens more detailed view

Detailed view includes also information about sharing (with whom, when etc)

**Comment by peeterkk** [comment]
@LiisiMotsharg with an option to unshare...

**Comment by peeterkk** [comment]
@LiisiMotsharg You don't usually just share it with one person. So you need to show a list of people, who you have shared it with.

**Comment by LiisiMotsharg** [comment]
Sharing was pushed to 3rd iteration. Functionality for displaying more detailed information about file is implemented, but not used at the moment.

Beyond that, user is shown a list of files he has on dropbox. He can see filename, size, date when file was last modified by server and by client (these are default properties returned by Dropbox API).

**Comment by LiisiMotsharg** [comment]
Sharing was not implemented during the course. Other than that, all functionality is present.
