### ISSUE TITLE
View for deleting files from Dropbox

### ISSUE THREAD

**Issue by peeterkk** [marinan87/smartsafe#43]
**Acceptance criteria**
- For each file in a list, there is a clickable button that deletes file from DropBox.
- User is shown confirmation.
- File is only deleted if user confirms his wish.
- If user cancels deletion, file is not deleted.

**Comment by LiisiMotsharg** [comment]
Maybe just add a button next to a file in a list of files? I don't see a need to have entire view just for deleting files.

**Comment by LiisiMotsharg** [comment]
Is related to #37

**Comment by peeterkk** [comment]
@LiisiMotsharg Do it in a way that makes the most sense from the user's perspective. The faster you can do it and the less you have to think, the better.

**Comment by LiisiMotsharg** [comment]
Added a button for deleting file (commit 905075d0c52ec52eebd5a167abffbf65d5c31ffb)
