### ISSUE TITLE
Look at the laws 

### ISSUE THREAD

**Issue by peeterkk** [marinan87/smartsafe#46]
The laws force companies to protect their data. Can we find any use cases from these obligations?

**Comment by lasertunguus** [comment]
EU's new _General Data Protection Regulation_ enforces more strict regulation on member states regarding data privacy.
See [Section 2, Article 32](http://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2016.119.01.0001.01.ENG&toc=OJ:L:2016:119:TOC).

>1.   Taking into account the state of the art, the costs of implementation and the nature, scope, context and purposes of processing as well as the risk of varying likelihood and severity for the rights and freedoms of natural persons, the controller and the processor shall implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk, including inter alia as appropriate:
>  (a) the pseudonymisation and encryption of personal data;
>  (b) the ability to ensure the ongoing confidentiality, integrity, availability and resilience of processing systems and services;
>  (c) the ability to restore the availability and access to personal data in a timely manner in the event of a physical or technical incident;
>  (d) a process for regularly testing, assessing and evaluating the effectiveness of technical and organisational measures for ensuring the security of the processing.

**Comment by lasertunguus** [comment]
Also, this can be the case with NDA's, where confidential data needs to be protected from 3rd parties.
