### ISSUE TITLE
Logging for client application

### ISSUE THREAD

**Issue by lasertunguus** [marinan87/smartsafe#53]
For better debugging we should use logging in our JS application.
A good and intuitive to use seems to be [winstonjs/winston](https://github.com/winstonjs/winston).

Logging levels (currently set to `debug`, adjustable in `utils/log.js`): 
`{ error: 0, warn: 1, info: 2, verbose: 3, debug: 4, silly: 5 }`

Usage:
1. use code below to use this logger:
    var logger = require('winston')
entrypoint js-file needs to have (index.js/server.js):
    var logger = require('<path_to_this_file>')
2. log with logger.<error|warn|info|debug>('...')
supports string interpolation as in
`var t = 'test'`
`logger.info('%s test', t) => test test`

No need to go crazy on this, just when it seems necessary or would be useful for debugging.

**Comment by peeterkk** [comment]
@lasertunguus console.log.bind(console) should be good enough. Don't overthink it.

**Comment by lasertunguus** [comment]
Closing for now. Before sending to UAT, file logging should be added.
